import type { WorkflowTransition } from '@inventory/shared';
import type { DemoAsset, DemoHolding, DemoPerson, DemoWorkflowStatus } from '@/types/demo.js';

/**
 * The demo company. Everything here is fictional and every address is under
 * `.example`, which RFC 2606 reserves precisely so a dataset like this can
 * never reach a real inbox.
 */
export const ORG_NAME = 'Northwind Robotics';
export const EMAIL_DOMAIN = 'northwind.example';

/** How far back the story starts. Old enough to have a history worth reading. */
export const HISTORY_DAYS = 132;

/**
 * When the one departure was announced. Check-ins before this day were done
 * by somebody who was still staying, so they read `returned`, not `offboarded`
 * — the outcome is a fact about the moment, not about who has left since.
 */
export const OFFBOARDING_DAYS_AGO = 4;

export const PEOPLE: DemoPerson[] = [
  {
    key: 'ada',
    firstName: 'Ada',
    lastName: 'Okafor',
    jobTitle: 'Head of IT',
    department: 'IT Operations',
    location: 'Berlin',
    startYearsAgo: 4,
    addedDaysAgo: 131,
    status: 'active',
    account: { role: 'admin', status: 'active' },
  },
  {
    key: 'marco',
    firstName: 'Marco',
    lastName: 'Rossi',
    jobTitle: 'Systems Engineer',
    department: 'IT Operations',
    location: 'Milan',
    startYearsAgo: 2,
    addedDaysAgo: 130,
    status: 'active',
    account: { role: 'manager', status: 'active' },
  },
  {
    key: 'lena',
    firstName: 'Lena',
    lastName: 'Fischer',
    jobTitle: 'Financial Analyst',
    department: 'Finance',
    location: 'Berlin',
    startYearsAgo: 3,
    addedDaysAgo: 129,
    status: 'active',
    account: { role: 'viewer', status: 'active' },
  },
  {
    key: 'priya',
    firstName: 'Priya',
    lastName: 'Raman',
    jobTitle: 'IT Support Specialist',
    department: 'IT Operations',
    location: 'Berlin',
    startYearsAgo: 0,
    addedDaysAgo: 9,
    status: 'active',
    // Invited but not yet accepted — the state the Members page draws in blue,
    // and the reason the invite link is worth showing on screen.
    account: { role: 'manager', status: 'invited' },
  },
  {
    key: 'yuki',
    firstName: 'Yuki',
    lastName: 'Tanaka',
    jobTitle: 'Senior Backend Engineer',
    department: 'Engineering',
    location: 'Berlin',
    startYearsAgo: 3,
    addedDaysAgo: 128,
    status: 'active',
  },
  {
    key: 'sofia',
    firstName: 'Sofia',
    lastName: 'Almeida',
    jobTitle: 'Product Designer',
    department: 'Design',
    location: 'Lisbon',
    startYearsAgo: 2,
    addedDaysAgo: 127,
    status: 'active',
  },
  {
    key: 'tomas',
    firstName: 'Tomás',
    lastName: 'Herrera',
    jobTitle: 'Platform Engineer',
    department: 'Engineering',
    location: 'Madrid',
    startYearsAgo: 1,
    addedDaysAgo: 126,
    status: 'active',
  },
  {
    key: 'nadia',
    firstName: 'Nadia',
    lastName: 'Haddad',
    jobTitle: 'Content Lead',
    department: 'Marketing',
    location: 'Paris',
    startYearsAgo: 2,
    addedDaysAgo: 125,
    status: 'active',
  },
  {
    key: 'oliver',
    firstName: 'Oliver',
    lastName: 'Bennett',
    jobTitle: 'Account Executive',
    department: 'Sales',
    location: 'London',
    startYearsAgo: 1,
    addedDaysAgo: 124,
    status: 'active',
  },
  {
    key: 'mei',
    firstName: 'Mei',
    lastName: 'Lin',
    jobTitle: 'Mobile Engineer',
    department: 'Engineering',
    location: 'Berlin',
    startYearsAgo: 1,
    addedDaysAgo: 96,
    status: 'active',
  },
  {
    key: 'grace',
    firstName: 'Grace',
    lastName: 'Chen',
    jobTitle: 'Controller',
    department: 'Finance',
    location: 'London',
    startYearsAgo: 5,
    addedDaysAgo: 123,
    status: 'active',
  },
  {
    key: 'jonas',
    firstName: 'Jonas',
    lastName: 'Weber',
    jobTitle: 'Design Systems Lead',
    department: 'Design',
    location: 'Hamburg',
    startYearsAgo: 3,
    addedDaysAgo: 122,
    // Leaving, which is what puts two devices in the Pending returns widget.
    status: 'offboarding',
  },
];

/**
 * The inventory. Warranty dates are offsets from the seeding clock so the
 * dashboard's 90-day window always has something in it: `warrantyInDays` under
 * 30 renders in the error colour, 30–90 as a warning.
 */
export const ASSETS: DemoAsset[] = [
  {
    key: 'mbp16',
    name: 'MacBook Pro 16" M3 Max',
    category: 'laptops',
    model: 'A2991',
    serialNumber: 'C02XK1AZQ6L7',
    priceEuros: 3499,
    supplier: 'Apple Business',
    purchasedDaysAgo: 400,
    warrantyInDays: 18,
    addedDaysAgo: 121,
    status: 'available',
    custom: { hostname: 'nw-mbp-0142', costCenter: 'ENG-01', mdm: true, encrypted: true },
  },
  {
    key: 'mbp14',
    name: 'MacBook Pro 14" M3',
    category: 'laptops',
    model: 'A2918',
    serialNumber: 'C02FL9QXQ6L4',
    priceEuros: 2299,
    supplier: 'Apple Business',
    purchasedDaysAgo: 300,
    warrantyInDays: 61,
    addedDaysAgo: 121,
    status: 'available',
    custom: { hostname: 'nw-mbp-0088', costCenter: 'DES-02', mdm: true, encrypted: true },
  },
  {
    key: 'mba-m2',
    name: 'MacBook Air M2',
    category: 'laptops',
    model: 'A2681',
    serialNumber: 'C02DR3FGQ6L9',
    priceEuros: 1399,
    supplier: 'Apple Business',
    purchasedDaysAgo: 520,
    warrantyInDays: -40,
    addedDaysAgo: 120,
    status: 'available',
    custom: { hostname: 'nw-mba-0031', costCenter: 'MKT-01', mdm: true, encrypted: true },
  },
  {
    key: 'x1c',
    name: 'ThinkPad X1 Carbon Gen 11',
    category: 'laptops',
    model: '21HM',
    serialNumber: 'LR0ABC12345',
    priceEuros: 1899,
    supplier: 'Lenovo Direct',
    purchasedDaysAgo: 260,
    warrantyInDays: 84,
    addedDaysAgo: 119,
    status: 'available',
    custom: { hostname: 'nw-tp-0209', costCenter: 'ENG-01', mdm: true, encrypted: true },
  },
  {
    key: 't14s',
    name: 'ThinkPad T14s Gen 4',
    category: 'laptops',
    model: '21F6',
    serialNumber: 'LR0XYZ98765',
    priceEuros: 1549,
    supplier: 'Lenovo Direct',
    purchasedDaysAgo: 180,
    warrantyInDays: 190,
    addedDaysAgo: 118,
    status: 'available',
    custom: { hostname: 'nw-tp-0210', costCenter: 'ENG-01', mdm: false, encrypted: true },
  },
  {
    key: 'xps15',
    name: 'Dell XPS 15',
    category: 'laptops',
    model: '9530',
    serialNumber: 'DL7J2K8',
    priceEuros: 2099,
    supplier: 'Dell Business',
    purchasedDaysAgo: 340,
    warrantyInDays: 27,
    addedDaysAgo: 117,
    status: 'available',
    custom: { hostname: 'nw-dl-0114', costCenter: 'SAL-01', mdm: true, encrypted: false },
  },
  {
    key: 'mba-m3',
    name: 'MacBook Air M3',
    category: 'laptops',
    model: 'A3113',
    serialNumber: 'C02QW8RTQ6M2',
    priceEuros: 1499,
    supplier: 'Apple Business',
    purchasedDaysAgo: 95,
    warrantyInDays: 635,
    addedDaysAgo: 95,
    status: 'available',
    custom: { hostname: 'nw-mba-0044', costCenter: 'ENG-02', mdm: true, encrypted: true },
  },
  {
    key: 'framework',
    name: 'Framework Laptop 13',
    category: 'laptops',
    model: 'FRANBZ',
    serialNumber: 'FW13A00291',
    priceEuros: 1249,
    supplier: 'Framework',
    purchasedDaysAgo: 220,
    warrantyInDays: 145,
    addedDaysAgo: 116,
    // Came back from its last holder needing repair, and is still at the shop.
    status: 'in_repair',
    custom: { hostname: 'nw-fw-0007', costCenter: 'ENG-01', mdm: false, encrypted: true },
  },
  {
    key: 'elitebook',
    name: 'HP EliteBook 840 G10',
    category: 'laptops',
    model: '8A3X1EA',
    serialNumber: 'HP5CD3210XY',
    priceEuros: 1699,
    supplier: 'HP Business',
    purchasedDaysAgo: 290,
    warrantyInDays: 75,
    addedDaysAgo: 115,
    status: 'available',
    custom: { hostname: 'nw-hp-0052', costCenter: 'DES-02', mdm: true, encrypted: true },
  },
  {
    key: 'macmini',
    name: 'Mac mini M2 Pro',
    category: 'desktops',
    model: 'A2816',
    serialNumber: 'C07TR4MNQ8P1',
    priceEuros: 1649,
    supplier: 'Apple Business',
    purchasedDaysAgo: 240,
    warrantyInDays: 125,
    addedDaysAgo: 114,
    status: 'available',
    custom: { hostname: 'nw-mm-0003', costCenter: 'ITO-01', mdm: true, encrypted: true },
  },
  {
    key: 'optiplex',
    name: 'Dell OptiPlex 7010',
    category: 'desktops',
    model: '7010MFF',
    serialNumber: 'DLOP77281',
    priceEuros: 899,
    supplier: 'Dell Business',
    purchasedDaysAgo: 410,
    warrantyInDays: 55,
    addedDaysAgo: 113,
    status: 'available',
  },
  {
    key: 'u2723-a',
    name: 'Dell UltraSharp U2723QE',
    category: 'monitors',
    model: 'U2723QE',
    serialNumber: 'CN0J2Y8A',
    priceEuros: 579,
    supplier: 'Dell Business',
    purchasedDaysAgo: 300,
    warrantyInDays: 430,
    addedDaysAgo: 112,
    status: 'available',
  },
  {
    key: 'u2723-b',
    name: 'Dell UltraSharp U2723QE',
    category: 'monitors',
    model: 'U2723QE',
    serialNumber: 'CN0J2Y8B',
    priceEuros: 579,
    supplier: 'Dell Business',
    purchasedDaysAgo: 300,
    warrantyInDays: 430,
    addedDaysAgo: 112,
    status: 'available',
  },
  {
    key: 'lg-ultrafine',
    name: 'LG UltraFine 27"',
    category: 'monitors',
    model: '27UN880',
    serialNumber: 'LG27UF0091',
    priceEuros: 649,
    supplier: 'LG Business',
    purchasedDaysAgo: 350,
    warrantyInDays: 210,
    addedDaysAgo: 111,
    status: 'available',
  },
  {
    key: 'studio-display',
    name: 'Apple Studio Display',
    category: 'monitors',
    model: 'A2525',
    serialNumber: 'C02SD9911QQ',
    priceEuros: 1749,
    supplier: 'Apple Business',
    purchasedDaysAgo: 200,
    warrantyInDays: 165,
    addedDaysAgo: 110,
    status: 'available',
  },
  {
    key: 'u2422',
    name: 'Dell UltraSharp U2422H',
    category: 'monitors',
    model: 'U2422H',
    serialNumber: 'CN0K5X1P',
    priceEuros: 329,
    supplier: 'Dell Business',
    purchasedDaysAgo: 480,
    warrantyInDays: 40,
    addedDaysAgo: 109,
    status: 'available',
  },
  {
    key: 'iphone15',
    name: 'iPhone 15 Pro',
    category: 'phones',
    model: 'A3102',
    serialNumber: 'F2LXK9P0Q1',
    priceEuros: 1199,
    supplier: 'Apple Business',
    purchasedDaysAgo: 150,
    warrantyInDays: 215,
    addedDaysAgo: 108,
    status: 'available',
  },
  {
    key: 'iphone14',
    name: 'iPhone 14',
    category: 'phones',
    model: 'A2882',
    serialNumber: 'F2MRT4W8Z2',
    priceEuros: 899,
    supplier: 'Apple Business',
    purchasedDaysAgo: 460,
    warrantyInDays: -95,
    addedDaysAgo: 107,
    status: 'available',
  },
  {
    key: 'pixel8',
    name: 'Google Pixel 8',
    category: 'phones',
    model: 'GKWS6',
    serialNumber: 'GP8N00483',
    priceEuros: 799,
    supplier: 'Google Store',
    purchasedDaysAgo: 4,
    warrantyInDays: 726,
    addedDaysAgo: 4,
    // On order: bought, not yet in anyone's hands.
    status: 'ordered',
  },
  {
    key: 'ipad-air',
    name: 'iPad Air M2',
    category: 'phones',
    model: 'A2902',
    serialNumber: 'DMPXQ1188',
    priceEuros: 749,
    supplier: 'Apple Business',
    purchasedDaysAgo: 2,
    warrantyInDays: 728,
    addedDaysAgo: 2,
    status: 'ordered',
  },
  {
    key: 'galaxy-s24',
    name: 'Samsung Galaxy S24',
    category: 'phones',
    model: 'SM-S921B',
    serialNumber: 'RF8W20ABCDE',
    priceEuros: 899,
    supplier: 'Samsung Business',
    purchasedDaysAgo: 260,
    warrantyInDays: 105,
    addedDaysAgo: 106,
    // Went missing on a trip and was written off — every status is on show.
    status: 'lost_stolen',
  },
  {
    key: 'mx-master',
    name: 'Logitech MX Master 3S',
    category: 'peripherals',
    model: '910-006559',
    serialNumber: 'LG3S001274',
    priceEuros: 109,
    supplier: 'Logitech',
    purchasedDaysAgo: 190,
    warrantyInDays: 175,
    addedDaysAgo: 105,
    status: 'available',
  },
  {
    key: 'mx-keys',
    name: 'Logitech MX Keys',
    category: 'peripherals',
    model: '920-009415',
    serialNumber: 'LGMK004411',
    priceEuros: 119,
    supplier: 'Logitech',
    purchasedDaysAgo: 190,
    warrantyInDays: 175,
    addedDaysAgo: 105,
    status: 'available',
  },
  {
    key: 'jabra',
    name: 'Jabra Evolve2 65',
    category: 'peripherals',
    model: '26599-989-999',
    serialNumber: 'JB65000912',
    priceEuros: 249,
    supplier: 'Jabra',
    purchasedDaysAgo: 210,
    warrantyInDays: 155,
    addedDaysAgo: 104,
    status: 'available',
  },
  {
    key: 'keychron',
    name: 'Keychron K3 Pro',
    category: 'peripherals',
    model: 'K3P-H3',
    serialNumber: 'KC3P00551',
    priceEuros: 99,
    supplier: 'Keychron',
    purchasedDaysAgo: 130,
    warrantyInDays: 235,
    addedDaysAgo: 103,
    status: 'available',
  },
  {
    key: 'mbp13-m1',
    name: 'MacBook Pro 13" M1',
    category: 'laptops',
    model: 'A2338',
    serialNumber: 'C02OLD1234X',
    priceEuros: 1499,
    supplier: 'Apple Business',
    purchasedDaysAgo: 1200,
    warrantyInDays: -470,
    addedDaysAgo: 102,
    // End of life: kept on the books so its history survives.
    status: 'retired',
  },
];

/**
 * Who held what, and when. Ordered by `fromDaysAgo` — the seeder replays them
 * in that order so the audit log reads as a story rather than a snapshot, and
 * so every close happens after its own open.
 *
 * A holding with no `untilDaysAgo` is still open, which is what makes its asset
 * `assigned`. Everything else is history, and the gaps between legs are what
 * the ownership timeline draws as "In stock".
 */
export const HOLDINGS: DemoHolding[] = [
  // A laptop that has been round the block: two holders, then a third.
  {
    assetKey: 'mbp16',
    personKey: 'tomas',
    fromDaysAgo: 118,
    untilDaysAgo: 74,
    condition: 'good',
    returnedTo: 'available',
    notes: 'Swapped for a machine with more memory.',
  },
  { assetKey: 'x1c', personKey: 'yuki', fromDaysAgo: 117, untilDaysAgo: 96, condition: 'good' },
  { assetKey: 'u2723-a', personKey: 'yuki', fromDaysAgo: 117 },
  { assetKey: 'mbp14', personKey: 'sofia', fromDaysAgo: 116 },
  { assetKey: 'lg-ultrafine', personKey: 'sofia', fromDaysAgo: 116 },
  { assetKey: 'mba-m2', personKey: 'nadia', fromDaysAgo: 114 },
  { assetKey: 'xps15', personKey: 'oliver', fromDaysAgo: 112 },
  { assetKey: 'iphone15', personKey: 'oliver', fromDaysAgo: 112 },
  { assetKey: 'macmini', personKey: 'marco', fromDaysAgo: 110 },
  { assetKey: 'mx-master', personKey: 'ada', fromDaysAgo: 108 },
  { assetKey: 'jabra', personKey: 'lena', fromDaysAgo: 106 },
  { assetKey: 'elitebook', personKey: 'jonas', fromDaysAgo: 104, dueInDays: 4 },
  { assetKey: 'u2422', personKey: 'jonas', fromDaysAgo: 104, dueInDays: 4 },
  // Broke, went back, and is still in repair.
  {
    assetKey: 'framework',
    personKey: 'grace',
    fromDaysAgo: 100,
    untilDaysAgo: 21,
    condition: 'needs_repair',
    returnedTo: 'in_repair',
    notes: 'Hinge cracked; sent to the supplier under warranty.',
  },
  { assetKey: 'x1c', personKey: 'tomas', fromDaysAgo: 92 },
  { assetKey: 'mbp16', personKey: 'yuki', fromDaysAgo: 70 },
  // A phone that came back before its owner left the company.
  {
    assetKey: 'iphone14',
    personKey: 'jonas',
    fromDaysAgo: 64,
    untilDaysAgo: 30,
    condition: 'good',
    returnedTo: 'available',
  },
  { assetKey: 'mba-m3', personKey: 'mei', fromDaysAgo: 60 },
  // The most recent handout, so the dashboard has something from this week.
  { assetKey: 'keychron', personKey: 'mei', fromDaysAgo: 2 },
];

/**
 * The status this company added for itself: a machine that has come back is
 * wiped and re-imaged before anybody else gets it. It is a check-in target and
 * deliberately not assignable — a device still being imaged is not one you can
 * hand somebody.
 */
export const DEMO_STATUS: DemoWorkflowStatus = {
  // What `statusSlug('In imaging')` derives, written down because the graph
  // below has to name it before the row exists.
  id: 'in_imaging',
  label: 'In imaging',
  color: 'info',
  assignableFrom: false,
  checkinTarget: true,
};

/**
 * The workflow the demo company settled on, replacing the full mesh a fresh
 * instance is seeded with. A mesh is the honest default — a new workspace has
 * no opinion — but it draws as a ball of arrows and demonstrates nothing, so
 * the demo shows a graph with a policy in it:
 *
 * a delivery is imaged or shelved, imaging ends in stock, an available machine
 * can break, be written off or be retired, repairs and recoveries go back to
 * the shelf or to the scrapheap — and retirement is where a device's story
 * ends, so it has no way out at all.
 */
export const DEMO_TRANSITIONS: readonly WorkflowTransition[] = [
  { from: 'ordered', to: DEMO_STATUS.id },
  { from: 'ordered', to: 'available' },
  { from: DEMO_STATUS.id, to: 'available' },
  { from: 'available', to: 'in_repair' },
  { from: 'available', to: 'retired' },
  { from: 'available', to: 'lost_stolen' },
  { from: 'in_repair', to: 'available' },
  { from: 'in_repair', to: 'retired' },
  { from: 'lost_stolen', to: 'available' },
  { from: 'lost_stolen', to: 'retired' },
];
