CREATE TABLE "asset_custom_values" (
	"asset_id" text NOT NULL,
	"field_def_id" text NOT NULL,
	"value" text,
	CONSTRAINT "asset_custom_values_asset_id_field_def_id_pk" PRIMARY KEY("asset_id","field_def_id")
);
--> statement-breakpoint
CREATE TABLE "asset_status_transitions" (
	"from_status" text NOT NULL,
	"to_status" text NOT NULL,
	CONSTRAINT "asset_status_transitions_from_status_to_status_pk" PRIMARY KEY("from_status","to_status")
);
--> statement-breakpoint
CREATE TABLE "asset_statuses" (
	"id" text PRIMARY KEY NOT NULL,
	"label" text NOT NULL,
	"color" text NOT NULL,
	"is_system" boolean DEFAULT false NOT NULL,
	"assignable_from" boolean DEFAULT false NOT NULL,
	"checkin_target" boolean DEFAULT false NOT NULL,
	"sort_order" integer NOT NULL,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL,
	CONSTRAINT "asset_statuses_label_unique" UNIQUE("label")
);
--> statement-breakpoint
CREATE TABLE "assets" (
	"id" text PRIMARY KEY NOT NULL,
	"asset_tag" text NOT NULL,
	"name" text NOT NULL,
	"category" text NOT NULL,
	"model" text,
	"serial_number" text,
	"status" text DEFAULT 'available' NOT NULL,
	"purchase_date" text,
	"purchase_price_cents" integer,
	"currency" text,
	"supplier" text,
	"warranty_until" text,
	"notes" text,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL,
	CONSTRAINT "assets_asset_tag_unique" UNIQUE("asset_tag")
);
--> statement-breakpoint
CREATE TABLE "assignments" (
	"id" text PRIMARY KEY NOT NULL,
	"asset_id" text NOT NULL,
	"employee_id" text,
	"holder_name_snapshot" text NOT NULL,
	"checked_out_at" text NOT NULL,
	"expected_return_date" text,
	"returned_at" text,
	"checkout_notes" text,
	"checkin_condition" text,
	"checkin_new_status" text,
	"checkin_notes" text,
	"outcome" text,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "attachments" (
	"id" text PRIMARY KEY NOT NULL,
	"asset_id" text NOT NULL,
	"filename" text NOT NULL,
	"stored_name" text NOT NULL,
	"size_bytes" integer NOT NULL,
	"sha256" text,
	"mime" text,
	"uploaded_by_member_id" text,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "audit_events" (
	"id" text PRIMARY KEY NOT NULL,
	"at" text NOT NULL,
	"type" text NOT NULL,
	"action" text NOT NULL,
	"actor_member_id" text,
	"actor_name" text NOT NULL,
	"asset_id" text,
	"employee_id" text,
	"member_id" text,
	"params" text DEFAULT '{}' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "auth_tokens" (
	"id" text PRIMARY KEY NOT NULL,
	"member_id" text NOT NULL,
	"purpose" text NOT NULL,
	"expires_at" text NOT NULL,
	"consumed_at" text,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "custom_field_defs" (
	"id" text PRIMARY KEY NOT NULL,
	"key" text NOT NULL,
	"label" text NOT NULL,
	"type" text NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" text NOT NULL,
	CONSTRAINT "custom_field_defs_key_unique" UNIQUE("key")
);
--> statement-breakpoint
CREATE TABLE "employees" (
	"id" text PRIMARY KEY NOT NULL,
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"email" text NOT NULL,
	"job_title" text,
	"department" text,
	"location" text,
	"employee_code" text,
	"start_date" text,
	"status" text DEFAULT 'active' NOT NULL,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL,
	CONSTRAINT "employees_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "members" (
	"id" text PRIMARY KEY NOT NULL,
	"email" text NOT NULL,
	"display_name" text NOT NULL,
	"password_hash" text,
	"role" text NOT NULL,
	"status" text NOT NULL,
	"employee_id" text,
	"last_active_at" text,
	"mfa_secret" text,
	"mfa_confirmed_at" text,
	"theme" text DEFAULT 'light' NOT NULL,
	"density" text DEFAULT 'comfortable' NOT NULL,
	"widgets_json" text DEFAULT '{}' NOT NULL,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL,
	CONSTRAINT "members_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "mfa_recovery_codes" (
	"id" text PRIMARY KEY NOT NULL,
	"member_id" text NOT NULL,
	"code_hash" text NOT NULL,
	"used_at" text,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "notification_log" (
	"id" text PRIMARY KEY NOT NULL,
	"kind" text NOT NULL,
	"dedupe_key" text NOT NULL,
	"sent_at" text NOT NULL,
	CONSTRAINT "notification_log_dedupe_key_unique" UNIQUE("dedupe_key")
);
--> statement-breakpoint
CREATE TABLE "org_settings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "org_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"org_name" text NOT NULL,
	"default_currency" text DEFAULT 'EUR' NOT NULL,
	"asset_tag_prefix" text DEFAULT 'AST' NOT NULL,
	"warranty_lead_days" integer DEFAULT 60 NOT NULL,
	"log_retention_months" integer,
	"email_warranty_alerts" boolean DEFAULT true NOT NULL,
	"email_return_reminders" boolean DEFAULT true NOT NULL,
	"email_invites" boolean DEFAULT true NOT NULL,
	"email_weekly_digest" boolean DEFAULT false NOT NULL,
	"mfa_required" boolean DEFAULT false NOT NULL,
	"upload_quota_mb" integer DEFAULT 2048 NOT NULL,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "role_permissions" (
	"role_id" text NOT NULL,
	"action" text NOT NULL,
	CONSTRAINT "role_permissions_role_id_action_pk" PRIMARY KEY("role_id","action")
);
--> statement-breakpoint
CREATE TABLE "roles" (
	"id" text PRIMARY KEY NOT NULL,
	"label" text NOT NULL,
	"description" text,
	"color" text NOT NULL,
	"is_system" boolean DEFAULT false NOT NULL,
	"sort_order" integer NOT NULL,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL,
	CONSTRAINT "roles_label_unique" UNIQUE("label")
);
--> statement-breakpoint
CREATE TABLE "sessions" (
	"id" text PRIMARY KEY NOT NULL,
	"member_id" text NOT NULL,
	"expires_at" text NOT NULL,
	"created_at" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "asset_custom_values" ADD CONSTRAINT "asset_custom_values_asset_id_assets_id_fk" FOREIGN KEY ("asset_id") REFERENCES "public"."assets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "asset_custom_values" ADD CONSTRAINT "asset_custom_values_field_def_id_custom_field_defs_id_fk" FOREIGN KEY ("field_def_id") REFERENCES "public"."custom_field_defs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "asset_status_transitions" ADD CONSTRAINT "asset_status_transitions_from_status_asset_statuses_id_fk" FOREIGN KEY ("from_status") REFERENCES "public"."asset_statuses"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "asset_status_transitions" ADD CONSTRAINT "asset_status_transitions_to_status_asset_statuses_id_fk" FOREIGN KEY ("to_status") REFERENCES "public"."asset_statuses"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "assignments" ADD CONSTRAINT "assignments_asset_id_assets_id_fk" FOREIGN KEY ("asset_id") REFERENCES "public"."assets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "assignments" ADD CONSTRAINT "assignments_employee_id_employees_id_fk" FOREIGN KEY ("employee_id") REFERENCES "public"."employees"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attachments" ADD CONSTRAINT "attachments_asset_id_assets_id_fk" FOREIGN KEY ("asset_id") REFERENCES "public"."assets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attachments" ADD CONSTRAINT "attachments_uploaded_by_member_id_members_id_fk" FOREIGN KEY ("uploaded_by_member_id") REFERENCES "public"."members"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_events" ADD CONSTRAINT "audit_events_actor_member_id_members_id_fk" FOREIGN KEY ("actor_member_id") REFERENCES "public"."members"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_tokens" ADD CONSTRAINT "auth_tokens_member_id_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."members"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "members" ADD CONSTRAINT "members_employee_id_employees_id_fk" FOREIGN KEY ("employee_id") REFERENCES "public"."employees"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mfa_recovery_codes" ADD CONSTRAINT "mfa_recovery_codes_member_id_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."members"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_role_id_roles_id_fk" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_member_id_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."members"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "assets_status_idx" ON "assets" USING btree ("status");--> statement-breakpoint
CREATE INDEX "assets_category_idx" ON "assets" USING btree ("category");--> statement-breakpoint
CREATE INDEX "assets_warranty_idx" ON "assets" USING btree ("warranty_until");--> statement-breakpoint
CREATE UNIQUE INDEX "assignments_one_active_per_asset" ON "assignments" USING btree ("asset_id") WHERE returned_at IS NULL;--> statement-breakpoint
CREATE INDEX "assignments_employee_idx" ON "assignments" USING btree ("employee_id");--> statement-breakpoint
CREATE INDEX "assignments_asset_history_idx" ON "assignments" USING btree ("asset_id","checked_out_at");--> statement-breakpoint
CREATE INDEX "assignments_pending_return_idx" ON "assignments" USING btree ("expected_return_date") WHERE returned_at IS NULL;--> statement-breakpoint
CREATE INDEX "attachments_asset_idx" ON "attachments" USING btree ("asset_id");--> statement-breakpoint
CREATE INDEX "audit_at_idx" ON "audit_events" USING btree ("at");--> statement-breakpoint
CREATE INDEX "audit_asset_idx" ON "audit_events" USING btree ("asset_id","at");--> statement-breakpoint
CREATE INDEX "audit_type_idx" ON "audit_events" USING btree ("type","at");--> statement-breakpoint
CREATE INDEX "auth_tokens_member_idx" ON "auth_tokens" USING btree ("member_id","purpose");--> statement-breakpoint
CREATE INDEX "employees_status_idx" ON "employees" USING btree ("status");--> statement-breakpoint
CREATE INDEX "members_employee_idx" ON "members" USING btree ("employee_id");--> statement-breakpoint
CREATE INDEX "mfa_recovery_member_idx" ON "mfa_recovery_codes" USING btree ("member_id");--> statement-breakpoint
CREATE INDEX "sessions_member_idx" ON "sessions" USING btree ("member_id");--> statement-breakpoint
CREATE INDEX "sessions_expires_idx" ON "sessions" USING btree ("expires_at");